### ISSUE TITLE
swtpm_setup failed with exit_status 126 and empty log

### ISSUE THREAD

**Issue by NobodyXu** [stefanberger/swtpm#665]
**Describe the bug**

I am using `virt-manager` to create a vm to install windows 11.

```
Unable to complete install: 'internal error: Could not run '/usr/local/bin/swtpm_setup'. exitstatus: 126; Check error log '/var/log/swtpm/libvirt/qemu/win10-swtpm.log' for details.'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2001, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 701, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 649, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3.9/site-packages/libvirt.py", line 4393, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: internal error: Could not run '/usr/local/bin/swtpm_setup'. exitstatus: 126; Check error log '/var/log/swtpm/libvirt/qemu/win10-swtpm.log' for details.
```

**To Reproduce**

libvirt XML configure:

```
<domain type="kvm">
  <name>win10</name>
  <uuid>ea819988-dd9b-4ef3-891f-ac0a9a084198</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/10"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory>20520960</memory>
  <currentMemory>20520960</currentMemory>
  <vcpu>16</vcpu>
  <os>
    <type arch="x86_64" machine="q35">hvm</type>
    <loader readonly="yes" type="pflash" secure="yes">/usr/share/OVMF/OVMF_CODE_4M.secboot.fd</loader>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state="on"/>
      <vapic state="on"/>
      <spinlocks state="on" retries="8191"/>
    </hyperv>
    <vmport state="off"/>
    <smm state="on"/>
  </features>
  <cpu mode="host-model"/>
  <clock offset="localtime">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
    <timer name="hypervclock" present="yes"/>
  </clock>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="raw"/>
      <source file="/var/lib/libvirt/images/win11.img"/>
      <target dev="sda" bus="sata"/>
      <boot order="2"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw"/>
      <source file="/var/lib/libvirt/images/Win11_English_x64v1.iso"/>
      <target dev="sdb" bus="sata"/>
      <readonly/>
      <boot order="1"/>
    </disk>
    <controller type="usb" model="qemu-xhci" ports="15"/>
    <interface type="network">
      <source network="default"/>
      <mac address="52:54:00:73:22:e1"/>
      <model type="e1000e"/>
    </interface>
    <console type="pty"/>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
    </channel>
    <input type="tablet" bus="usb"/>
    <tpm model="tpm-crb">
      <backend type="emulator" version="2.0"/>
    </tpm>
    <graphics type="spice" port="-1" tlsPort="-1" autoport="yes"/>
    <sound model="ich9"/>
    <video>
      <model type="qxl"/>
    </video>
    <redirdev bus="usb" type="spicevmc"/>
    <redirdev bus="usb" type="spicevmc"/>
  </devices>
</domain>
```

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version: 21.10

**Versions of relevant components**
- swtpm: TPM emulator setup tool version 0.7.1
- libtpms: 0.8.2-1ubuntu1
- openssl: 1.1.1l-1ubuntu1.1
- libvirtd: libvirtd (libvirt) 7.6.0
- virt-manager: 3.2.0

**Log files**

`/var/log/swtpm/libvirt/qemu/win10-swtpm.log` is empty.

**Comment by NobodyXu** [comment]
I have figured out the problem, it was because of the apparmor.

**Comment by stefanberger** [comment]
> I have figured out the problem, it was because of the apparmor.

That would have been another guess. Good that you figured it out.
