### ISSUE TITLE
Error creating local CA's signing key and cert when used with QEMU/KVM and virt-manager

### ISSUE THREAD

**Issue by Duy-Thanh** [stefanberger/swtpm#699]
**Describe the bug**

Error creating local CA's signing key and cert when used with QEMU/KVM and virt-manager

**Expected behavior**

I added the TPM v2.0 device to my QEMU/KVM virtual machine, I use virt-manager and when I start the virtual machine an error message pops up:

```
Error starting domain: internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/var/log/swtpm/libvirt/qemu/win11-swtpm.log' for details.

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, print cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, print tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/var/log/swtpm/libvirt/qemu/win11-swtpm.log' for details.
```

When I run the following command in Terminal:

`cat /var/log/swtpm/libvirt/qemu/win11-swtpm.log`

Output will be:

```
Starting vTPM manufacturing as swtpm:swtpm @ Wed 18 May 2022 08:22:05 PM +07
Successfully created RSA 2048 EK with handle 0x81010001.
  Invoking /usr/lib/x86_64-linux-gnu/swtpm/swtpm-localca --type ek --ek ab317b8914e40472268886a18685e84d720acbd8d23496f62a8b5bdb9eeffdd4eb5b04b829b6176973ee38f3fed148e77bc03600b24eae0ce69b64e41a3ff4b736a29d6eb6ab664b87f123956e40666a4079f9291e2d944cc22ca084ec3d43516e38e3276de03efe2c4a681db73d8807f60fdc0a63e20fc95bd0faabcf3f13155b91a8bcfeb4a6db00de13c7ecb298d777029accfa685796de1e2b4f4f89c1e8b7331bed7bf4594f050ba2482edd8da92f2a046fd7e6258ab1907559f132c5955a5684e9443106f7dc5010a4f97372844b8682f71193e1aade813a11a1b5cc91a3fb1861a073d4dbf39734da44e4faf981d9f77d668b08abbb5235b3b766f75b --dir /var/lib/libvirt/swtpm/4808adac-8d26-477f-a6d4-f534eba97fea/tpm2 --logfile /var/log/swtpm/libvirt/qemu/win11-swtpm.log --vmid win7:4808adac-8d26-477f-a6d4-f534eba97fea --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 164 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20191023 --tpm2 --configfile /etc/swtpm-localca.conf --optsfile /etc/swtpm-localca.options
Creating root CA and a local CA's signing key and issuer cert.
Could not create root-CA key /var/lib/swtpm-localca/swtpm-localca-rootca-privkey.pem:genrsa: Unrecognized flag traditional

Error creating local CA's signing key and cert.
swtpm-localca exit with status 1: 
An error occurred. Authoring the TPM state failed.
Ending vTPM manufacturing @ Wed 18 May 2022 08:22:05 PM +07
```

**Desktop (please complete the following information):**
 - OS: [e.g.Fedora] Ubuntu 22.04 LTS (Linux nguyenduythanh-VivoBook-ASUSLaptop-X409FA-X409FA 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)
 - Version [e.g. 33] 22.04 LTS

**Versions of relevant components**
- swtpm: TPM emulator version 0.6.3, Copyright (c) 2014-2021 IBM Corp.
- libtpms: 0.9.3
- openssl: OpenSSL 1.1.1n  15 Mar 2022
- gnutls: 3.7.5
- ...:

**Comment by stefanberger** [comment]
> ```
> Could not create root-CA key /var/lib/swtpm-localca/swtpm-localca-rootca-privkey.pem:genrsa: Unrecognized flag traditional
> ```

What is 'flag traditional'? I have never seen this error. Looks like a backwards compatibility issue of some sort. 

Does this also appear when you run the following as root?

```
# swtpm_setup --tpm2 --tpmstate /tmp --create-ek-cert --overwrite
```

**Comment by stefanberger** [comment]
I see now what this is due to. Ubuntu 22.04 patched swtpm to use openssl rather than gnutls. Their patch is in this file here: archive.ubuntu.com/ubuntu/pool/main/s/swtpm/swtpm_0.6.3-0ubuntu3.debian.tar.xz

This is where the issue comes from with `--traditional`
```
+        openssl_env = g_environ_setenv(NULL, "PATH", g_getenv("PATH"), TRUE);
+
         /* generate the root-CA's private key */
         cmd = concat_arrays(cmd, (gchar*[]){
-                                (gchar *)certtool, "--generate-privkey", "--outfile", cakey, NULL
+			openssl, "genrsa", "-traditional", "-out", cakey, NULL
                             }, TRUE);
```

There was an open PR to this project here about this stuff which seemed to have become inactive following my suggestions, so I closed it: https://github.com/stefanberger/swtpm/pull/620

`--traditional` was introduced with OpenSSL 3.0. So they may have a dependency issue in Ubuntu because swtpm now depends on OpenSSL 3.0 to be installed to work properly. Please file a bug with Ubuntu about this.

**Comment by Duy-Thanh** [comment]
> I see now what this is due to. Ubuntu 22.04 patched swtpm to use openssl rather than gnutls. Their patch is in this file here: archive.ubuntu.com/ubuntu/pool/main/s/swtpm/swtpm_0.6.3-0ubuntu3.debian.tar.xz
> 
> This is where the issue comes from with `--traditional`
> 
> ```
> +        openssl_env = g_environ_setenv(NULL, "PATH", g_getenv("PATH"), TRUE);
> +
>          /* generate the root-CA's private key */
>          cmd = concat_arrays(cmd, (gchar*[]){
> -                                (gchar *)certtool, "--generate-privkey", "--outfile", cakey, NULL
> +			openssl, "genrsa", "-traditional", "-out", cakey, NULL
>                              }, TRUE);
> ```
> 
> There was an open PR to this project here about this stuff which seemed to have become inactive following my suggestions, so I closed it: #620
> 
> `--traditional` was introduced with OpenSSL 3.0. So they may have a dependency issue in Ubuntu because swtpm now depends on OpenSSL 3.0 to be installed to work properly. Please file a bug with Ubuntu about this.

I downloaded and installed OpenSSL on the OpenSSL homepage, and it worked
```
root@nguyenduythanh-VivoBook-ASUSLaptop-X409FA-X409FA:/home/nguyenduythanh# openssl version
OpenSSL 3.0.3 3 May 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
root@nguyenduythanh-VivoBook-ASUSLaptop-X409FA-X409FA:/home/nguyenduythanh# swtpm_setup --tpm2 --tpmstate /tmp --create-ek-cert --overwrite
Starting vTPM manufacturing as root:root @ Wed 18 May 2022 09:28:20 PM +07
TPM is listening on Unix socket.
Successfully created RSA 2048 EK with handle 0x81010001.
  Invoking /usr/lib/x86_64-linux-gnu/swtpm/swtpm-localca --type ek --ek 91ae25c9b45af5ff790a2cbdd8c1ec525db776a509d1e0820ea90ccf5adc30097c38ec0e215eec2b78777ce06ce22aa7547c12897a17a241d17c058d408d70923cf04a8a00be479e8d77cba2064063e3c1fcb6e831a07551f8af50b9a07ff1dbeafe7cf5e70bbf4f8b3c890945bb8a620f99709a6bd5fb6e6a5560e5cfc32d21d55a012d03c7eb4446c344ec6a845c673a872df67d5eea9f968bd99c5a59f9e47aad6830461e941d8ea43e086530e9f1c7da941bda0dea3acfe93c34d2a0edb8677264155cbbdf4d539d2ade0ec542647f4edacc2f597214636920647b6a32e0e0c541e264e56d0c70333571fd4f1554d4f5187f11f99e146158da2a378d9f03 --dir /tmp --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm- spec-revision 164 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20191023 --tpm2 --configfile /etc/swtpm-localca.conf --optsfile /etc/swtpm-localca. options
swtpm-localca: Successfully created EK certificate locally.
Successfully created NVRAM area 0x1c00002 for RSA 2048 EK certificate.
Successfully created ECC EK with handle 0x81010016.
  Invoking /usr/lib/x86_64-linux-gnu/swtpm/swtpm-localca --type ek --ek x=d059dd4e00f8566a2d0c59bae5f681a397616e33fa59316292c2f30fbb0c06c43a951c8ecf2c28f53915fe45b0a608e6,y=9e88dc1d9c72056ac9ddf81b8c0e13fbe66979419e76f30769325a8bf419aeb0afcf783df940d3d82665150e1212c2af,id=secp384r1 --dir /tmp --tpm-spec-family 2.0 -- tpm-spec-level 0 --tpm-spec-revision 164 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20191023 --tpm2 --configfile /etc/swtpm-localca.conf --optsfile /etc/swtpm-localca.options
swtpm-localca: Successfully created EK certificate locally.
Successfully created NVRAM area 0x1c00016 for ECC EK certificate.
Successfully activated PCR banks sha1,sha256 among sha1,sha256,sha384,sha512.
Successfully authored TPM state.
Ending vTPM manufacturing @ Wed 18 May 2022 09:28:20 PM +07
```

This is strange because version 1.1.1 of OpenSSL is currently under active development, and not everyone knows about this issue and installs a new version of OpenSSL, so I will report this to the Ubuntu team.

Anyway, thank you for helping me solve the problem

**Comment by stefanberger** [comment]
Thanks. Please post a link here or cc me when you report this issue to Ubuntu.
