### ISSUE TITLE
Could not find @DATAROOTDIR@/swtpm/swtpm-localca in PATH in libvirt on Ubuntu 22.04

### ISSUE THREAD

**Issue by jptrmn** [stefanberger/swtpm#749]
**Describe the bug**
Hi, I am unable to launch a libvirt user session with a tpm-tis TPM-2 Module.
When I launch the VM, I get the error: `Could not find @DATAROOTDIR@/swtpm/swtpm-localca in PATH.`

**To Reproduce**
1. Install swtpm
2. add a `tpm-tis` model TPMv2.0 to a user session in virt manager
3. create an AppArmor Profile with `aa-complain` for swtpm
4. Start VM

**Expected behavior**
I would expect libvirt to find and execute the `swtpm-localca` binary (located in `/usr/lib/x86_64-linux-gnu/swtpm/swtpm-localca` ) and create the appropriate files; Launch the VM.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04 LTS

**Versions of relevant components**
- swtpm: 0.6.3-0ubuntu3
- libtpms: 0.9.3-0ubuntu1
- openssl: 3.0.2-0ubuntu1.6 
- libgnutls: 3.7.3-4ubuntu1.1
- libvirt-daemon: 8.0.0-1ubuntu7.1
- qemu-utils: 1:6.2+dfsg-2ubuntu6.3

**Log files**
Please attach any log files. If using a VM and it was started with libvirt, attach the logfile  found in `/var/log/swtpm/libvirt/qemu/VM-NAME-swtpm.log`.

Virt Manager Output:
```
Fehler beim Starten der Domain: internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/home/josef/.cache/libvirt/qemu/log/win10-swtpm.log' for details.

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/home/josef/.cache/libvirt/qemu/log/win10-swtpm.log' for details.
```

The `win10-swtpm.log`:
```
Starting vTPM manufacturing as josef:josef @ Wed 14 Sep 2022 03:36:06 PM CEST
Successfully created RSA 2048 EK with handle 0x81010001.
Could not find @DATAROOTDIR@/swtpm/swtpm-localca in PATH.
An error occurred. Authoring the TPM state failed.
Ending vTPM manufacturing @ Wed 14 Sep 2022 03:36:06 PM CEST
```

**Additional context**
I had to enable an AppArmor profile because initially the swtpm.log error was:

```
Starting vTPM manufacturing as josef:josef @ Wed 14 Sep 2022 12:44:47 PM CEST
swtpm process terminated unexpectedly.
Could not start the TPM 2.
An error occurred. Authoring the TPM state failed.
Ending vTPM manufacturing @ Wed 14 Sep 2022 12:44:47 PM CEST
```

```
kern.log:Sep 14 12:44:47 josef-T460s kernel: [23521.549692] audit: type=1400 audit(1663152287.776:649): apparmor="DENIED" operation="mknod" profile="swtpm" name="/home/josef/.config/libvirt/qemu/swtpm/ffdcb282-04d3-4fdd-a006-c435bde80529/tpm2/.swtpm_setup.pidfile" pid=31032 comm="swtpm" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
```

Any Input would be greatly appreciated.

Thanks,
Josef

**Comment by stefanberger** [comment]
I think I know where it may come from. Are you starting the VM as root or as a non-root user?

There seems to be a packaging error:
```
# grep DATAROOT /usr/share/swtpm/swtpm-create-user-config-files
create_certs_tool = @DATAROOTDIR@/swtpm/swtpm-localca
```
The @DATAROOTDIR@ shouldn't be there but should look like this after the `configure` step during build:

```
create_certs_tool = /usr/share/swtpm/swtpm-localca
```

At least when I build the package locally and install the package then the file `/usr/share/swtpm/swtpm-create-user-config-files` looks like this:

```
        cat <<_EOF_ > "${SWTPM_SETUP_CONF}"
create_certs_tool = /usr/share/swtpm/swtpm-localca
create_certs_tool_config = ${SWTPM_LOCALCA_CONF}
```

**Comment by jptrmn** [comment]
Where could I report this issue to the ubuntu packaging maintainers?

**Comment by stefanberger** [comment]
@jptrmn You would have to file it here I think: https://bugs.launchpad.net/ubuntu

You can reference what I said above. This must be a packaging error of some sort...

Thanks a lot!

**Comment by stefanberger** [comment]
@jptrmn If you have a link to the Bugreport on Launchpad, can you post it here as well, please.

**Comment by jptrmn** [comment]
> @jptrmn If you have a link to the Bugreport on Launchpad, can you post it here as well, please.

@stefanberger Sure, here is the link to Launchpad: https://bugs.launchpad.net/ubuntu/+source/swtpm/+bug/1989598

Best,
Josef

**Comment by robin-checkmk** [comment]
I wound up here, after upgrading my Ubuntu 22.04 to 24.04. I know the reason behind my error is different, but the error message is basically the same and this issue was the only relevant search result. So in case anyone ends up in my place: I deleted the files in `/home/$USER/.config/swtpm*` and recreated them: `/usr/share/swtpm/swtpm-create-user-config-files`. Afterwards everything was back to schwifty.
